/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    autoScroll: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 300,
                    autoScroll: true,
                    collapseFirst: false,
                    collapsible: true,
                    title: 'FOP Development Group - www.fopdevelopmentgroup.com',
                    items: [
                        {
                            xtype: 'gridpanel',
                            floating: false,
                            id: 'projects',
                            autoScroll: false,
                            overlapHeader: true,
                            title: 'Press on the column title to resort this table',
                            titleCollapse: false,
                            forceFit: true,
                            scroll: 'vertical',
                            store: 'fopmatrix',
                            columnLines: true,
                            viewConfig: {
                                autoScroll: true,
                                blockRefresh: false
                            },
                            features: [
                                {
                                    ftype: 'grouping',
                                    enableGroupingMenu: false,
                                    enableNoGroups: false
                                }
                            ],
                            selModel: Ext.create('Ext.selection.RowModel', {
                                listeners: {
                                    select: {
                                        fn: me.onRowselectionmodelSelect,
                                        scope: me
                                    }
                                }
                            }),
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'project',
                                    text: 'Instulation / Project Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'capacity',
                                    text: 'Capacity in gpd'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'volume',
                                    text: 'Dwellings Served'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'category',
                                    text: 'Market Segmentation'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'footprint',
                                    text: 'Footprint'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'above',
                                    text: 'Above / Below Ground'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    id: 'bottomtab',
                    itemId: 'bottomtab',
                    stateId: 'bottomtab',
                    title: 'Detail Information - images and PDF files',
                    activeTab: 0
                }
            ]
        });

        me.callParent(arguments);
    },

    onRowselectionmodelSelect: function(rowmodel, record, index, options) {
        Ext.getCmp('bottomtab').removeAll();
        Ext.getCmp('bottomtab').add({ title: record.get("imagename"), autoScroll: 'true', html: '<IFRAME src="' + record.get("image") + '" width="' + record.get("width") + '" height="' + record.get("height") + '" frameborder="0"></IFRAME>' });
        Ext.getCmp('bottomtab').add({ title: record.get("PDFname"), autoScroll: 'true', html: '<IFRAME src="' + record.get("pdf") + '" width="' + record.get("pdfwidth") + '" height="' + record.get("pdfheight") + '" frameborder="0"></IFRAME>' });

    }

});