/*
 * File: app/model/matrix.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.matrix', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'project'
        },
        {
            name: 'imagename'
        },
        {
            name: 'capacity'
        },
        {
            name: 'volume'
        },
        {
            name: 'category'
        },
        {
            name: 'footprint'
        },
        {
            name: 'above'
        },
        {
            name: 'image'
        },
        {
            name: 'width'
        },
        {
            name: 'height'
        },
        {
            name: 'pdf'
        },
        {
            name: 'PDFname'
        },
        {
            name: 'pdfwidth'
        },
        {
            name: 'pdfheight'
        }
    ]
});