/*
 * File: app/view/MyPanel1.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel1', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel1',

    height: 675,
    html: '<p>It is a power generator, as opposed to power saver, which can significantly offset the electrical cost of running wastewater treatment plants, refineries, food processing of all types, mining operations (active and spent), paper and pulp operations, and chemical plants.</p>\n<p>It is a power generator, as opposed to power saver, which can significantly offset the electrical cost of running wastewater treatment plants, refineries, food processing of all types, mining operations (active and spent), paper and pulp operations, and chemical plants.</p>\n<p>It is a power generator, as opposed to power saver, which can significantly offset the electrical cost of running wastewater treatment plants, refineries, food processing of all types, mining operations (active and spent), paper and pulp operations, and chemical plants.</p>',
    title: 'Private Development',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});